resources:
- name: ci-repo
  type: git
  check_every: 1m
  icon: github
  source:
    uri: https://((ci-repo.host))/((ci-repo.slug))
    branch: ((ci-repo.branch))
jobs:

- name: job-static
  plan:
  - in_parallel:
    - get: ci-repo
      trigger: true
  - task: task-static
    file: ci-repo/concourse_examples/ci/tasks/task-static/task.yml

- name: job-create-and-consume
  public: true
  plan:
  - in_parallel:
    - get: ci-repo
      trigger: true
      passed: [ job-static ]
  - task: make-a-file
    file: ci-repo/concourse_examples/ci/tasks/task-create-and-consume/make-a-file-task.yml
  - task: consume-the-file
    file: ci-repo/concourse_examples/ci/tasks/task-create-and-consume/consume-the-file-task.yml